#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Grava sempre no .env da raiz do repo, de onde quer que o script rode.
ENV_FILE="${ENV_FILE:-$(cd "$(dirname "$0")/.." && pwd)/.env}"

TOTAL_STAGES=8
REDIRECT_PROD="https://chat.toneli.dev.br/api/connectors/google/callback"
REDIRECT_DEV="http://localhost:8000/api/connectors/google/callback"

banner "Conector Google (Gmail + Drive) — console do Google Cloud"

stage "Criar o projeto"
say "Faz login no navegador com a conta Google do Toneli."
open_url "https://console.cloud.google.com/projectcreate"
step "Project name: desafio-chat. Location: No organization."
step "Clica Create. Na notificação, clica Select project."
note "Confirma: o seletor no topo mostra desafio-chat."
pause "Projeto criado e selecionado? Enter"

stage "Habilitar Gmail API e Google Drive API"
open_url "https://console.cloud.google.com/apis/library/gmail.googleapis.com"
step "Clica Enable na Gmail API."
pause "Enter para abrir a Drive API"
open_url "https://console.cloud.google.com/apis/library/drive.googleapis.com"
step "Clica Enable na Google Drive API."
note "Confirma: https://console.cloud.google.com/apis/dashboard lista as duas."
pause "As duas APIs estão habilitadas? Enter"

stage "Consent screen (External, Testing)"
open_url "https://console.cloud.google.com/auth/overview"
step "Clica Get started."
step "App name: Desafio Chat. User support email: o do Toneli. Next."
step "Audience: External. Next."
step "Contact Information: o e-mail do Toneli. Next."
step "Aceita a User Data Policy. Continue. Create."
warn "Não clica Publish app. O app fica em Testing."
note "Confirma: /auth/audience mostra Publishing status Testing e User type External."
pause "Consent screen criada? Enter"

stage "Escopos gmail.readonly e drive.readonly"
open_url "https://console.cloud.google.com/auth/scopes"
step "Clica Add or remove scopes."
step "Filtra gmail.readonly e marca .../auth/gmail.readonly."
step "Filtra drive.readonly e marca .../auth/drive.readonly."
step "Clica Update. Depois Save no fim da página."
note "Confirma: Your restricted scopes lista os dois."
pause "Escopos salvos? Enter"

stage "Test users"
ask CPO_EMAIL "E-mail Google do CPO (só para exibir, não vai pro .env):"
open_url "https://console.cloud.google.com/auth/audience"
step "Em Test users, clica Add users."
step "Adiciona o e-mail do Toneli."
step "Adiciona: ${CPO_EMAIL:-<e-mail do CPO>}"
step "Clica Save."
note "Confirma: a lista mostra os dois e-mails."
pause "Test users salvos? Enter"

stage "Client OAuth Web application"
open_url "https://console.cloud.google.com/auth/clients/create"
step "Application type: Web application. Name: desafio-chat-web."
step "Authorized JavaScript origins: deixa vazio."
step "Authorized redirect URIs, Add URI: $REDIRECT_PROD"
step "Add URI de novo: $REDIRECT_DEV"
step "Clica Create."
warn "Clica Download JSON agora. O secret pode não aparecer de novo."
pause "Client criado e JSON baixado? Enter"

stage "Gravar client id e secret no .env"
ask GOOGLE_CLIENT_ID "Cola o Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Cola o Client secret (entrada oculta):"
if [[ "$GOOGLE_CLIENT_ID" != *.apps.googleusercontent.com ]]; then
  warn "Client ID não termina em .apps.googleusercontent.com. Confere a cópia."
fi
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
pause "Enter para o teste de fumaça"

stage "Teste de fumaça (sem o app)"
SCOPES="https://www.googleapis.com/auth/gmail.readonly%20https://www.googleapis.com/auth/drive.readonly"
open_url "https://accounts.google.com/o/oauth2/v2/auth?client_id=${GOOGLE_CLIENT_ID}&redirect_uri=${REDIRECT_DEV}&response_type=code&access_type=offline&prompt=consent&scope=${SCOPES}"
step "Faz login com a conta do Toneli."
step "No aviso 'Google hasn't verified this app', clica Continue."
step "Marca os dois acessos e clica Continue."
note "Sucesso: a barra de endereço vai para localhost:8000/...callback?code=..."
note "Erro de conexão na página é normal se a API não estiver rodando."
note "redirect_uri_mismatch: URI diferente, ou mudança ainda propagando."
note "access_denied: e-mail fora dos test users."
pause "Viu o code= na URL? Enter"

finish
